{
  "openapi": "3.0.1",
  "info": {
    "title": "test API",
    "version": "v1"
  },
  "tags": [
    {
      "name": "Users API:",
      "description": "main path - https://yummy-rest-api.yurgo.fun/"
    }
  ],
  "paths": {
    "/api/auth/register": {
      "post": {
        "summary": "Register a new user",
        "tags": [
          "Auth"
        ],
        "description": "description",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "example": {
                "name": "newUser",
                "email": "example@example.com",
                "password": "hsy36djhwe93"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "user": {
                      "type": "object",
                      "properties": {
                        "id": {
                          "type": "string",
                          "example": "hs672ijnfy23hf3pi3uwkdj"
                        },
                        "name": {
                          "type": "string",
                          "example": "newUser"
                        },
                        "email": {
                          "type": "string",
                          "example": "example@example.com"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "409": {
            "description": "Conflict",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "name already used"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/auth/login": {
      "post": {
        "summary": "Login existed user",
        "tags": [
          "Auth"
        ],
        "description": "description",
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "example": {
                "email": "Jimmy2updated@email.com",
                "password": "1234567"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "success"
                    },
                    "code": {
                      "type": "number",
                      "example": 200
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "email": {
                          "type": "string",
                          "example": "example@example.com"
                        },
                        "token": {
                          "type": "string",
                          "example": "eyJhbGeiO6JIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY0M2JiM2ZjZDgxNWZhNzcyYjU2N2M0ZSIsImlhdCI6MTY4MTY2ODYzNywiZXhwIjoxNjgxRjc1ODM3fQ.U2MKPZbgFvq_ASqX79dZBxOA7AbUncCQeH9M8ffohps"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "error email is required"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Email or password is wrong"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/auth/current": {
      "get": {
        "summary": "Get info of loginned user",
        "tags": [
          "Auth"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "success"
                    },
                    "code": {
                      "type": "number",
                      "example": 201
                    },
                    "message": {
                      "type": "string",
                      "example": "fields update"
                    },
                    "user": {
                      "type": "object",
                      "properties": {
                        "name": {
                          "type": "string",
                          "example": "UserName"
                        },
                        "email": {
                          "type": "string",
                          "example": "example@example.com"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not authorized"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/auth/{id}": {
      "put": {
        "summary": "Update existed user",
        "tags": [
          "Auth"
        ],
        "description": "Update name OR email fields os user record",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "user id",
            "schema": {
              "type": "string",
              "example": "6435681c54d50f705952fa96"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "example": {
                "name": "newName",
                "email": "Jimmy2updated@email.com"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "success"
                    },
                    "code": {
                      "type": "number",
                      "example": 201
                    },
                    "message": {
                      "type": "string",
                      "example": "fields update"
                    },
                    "data": {
                      "type": "object",
                      "properties": {
                        "updatedUser": {
                          "type": "object"
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "Not authorized"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/auth/logout": {
      "get": {
        "summary": "Update existed user",
        "tags": [
          "Auth"
        ],
        "description": "Logout loginned in user",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          }
        }
      }
    },
    "/api/subscribe": {
      "post": {
        "summary": "Subscribe to news feed",
        "tags": [
          "Subscribe"
        ],
        "description": "description",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Subscribe"
              },
              "example": {
                "emailToSubscribe": "example@email.com"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "subscribed": {
                      "type": "string",
                      "example": "email@email.com"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/recipes/category-list": {
      "get": {
        "summary": "Get a list of recipes categories",
        "tags": [
          "Receipes"
        ],
        "description": "received an array of strings",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Array of Strings - reccipes",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "categoryList": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      },
                      "example": [
                        "categ1",
                        "categ2",
                        "categ3"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/recipes/main-page": {
      "get": {
        "summary": "Get a list of recipes",
        "tags": [
          "Receipes"
        ],
        "description": "received an 4 receipes data for 4 categories",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Array of Strings - reccipes",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "success"
                    },
                    "code": {
                      "type": "number",
                      "example": 200
                    },
                    "flattenedResult": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "example": {
                          "id": "640cd5ac2d9fecf12e8897fc",
                          "title": "Spaghetti Bolognese",
                          "category": "Beef",
                          "area": "Italian,",
                          "instructions": "Put the onion and oil in a large pan and fry over a fairly high heat for 3-4 mins...",
                          "thumb": "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
                          "preview": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678560401/huqdxgwkvbhsfjqtexsm.jpg",
                          "time": 45,
                          "youtube": "https://www.youtube.com/watch?v=-gF8d-fitkU",
                          "tasgs": [
                            "Pasta",
                            "Meat"
                          ],
                          "ingredients": [
                            {
                              "measure": "2",
                              "id": "640c2dd963a319ea671e372e"
                            }
                          ]
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/recipes/category/{category}": {
      "get": {
        "summary": "Get a list of recipes by category",
        "tags": [
          "Receipes"
        ],
        "description": "received an 4 receipes data for 4 categories",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "category",
            "in": "path",
            "required": true,
            "description": "user id",
            "schema": {
              "type": "string",
              "example": "Chicken"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Array of Strings - reccipes",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "success"
                    },
                    "code": {
                      "type": "number",
                      "example": 200
                    },
                    "flattenedResult": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "example": {
                          "id": "640cd5ac2d9fecf12e8897fc",
                          "title": "Spaghetti Bolognese",
                          "category": "Beef",
                          "area": "Italian,",
                          "instructions": "Put the onion and oil in a large pan and fry over a fairly high heat for 3-4 mins...",
                          "thumb": "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
                          "preview": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678560401/huqdxgwkvbhsfjqtexsm.jpg",
                          "time": 45,
                          "youtube": "https://www.youtube.com/watch?v=-gF8d-fitkU",
                          "tasgs": [
                            "Pasta",
                            "Meat"
                          ],
                          "ingredients": [
                            {
                              "measure": "2",
                              "id": "640c2dd963a319ea671e372e"
                            }
                          ]
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "204": {
            "description": "when search has no result"
          }
        }
      }
    },
    "/api/recipes/id/{id}": {
      "get": {
        "summary": "Get a list of recipes",
        "tags": [
          "Receipes"
        ],
        "description": "received an 4 receipes data for 4 categories",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "user id",
            "schema": {
              "type": "string",
              "example": "640cd5ac2d9fecf12e8897f0"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "collection of reccipes",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "success"
                    },
                    "code": {
                      "type": "number",
                      "example": 200
                    },
                    "flattenedResult": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "example": {
                          "id": "640cd5ac2d9fecf12e8897fc",
                          "title": "Spaghetti Bolognese",
                          "category": "Beef",
                          "area": "Italian,",
                          "instructions": "Put the onion and oil in a large pan and fry over a fairly high heat for 3-4 mins...",
                          "thumb": "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
                          "preview": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678560401/huqdxgwkvbhsfjqtexsm.jpg",
                          "time": 45,
                          "youtube": "https://www.youtube.com/watch?v=-gF8d-fitkU",
                          "tasgs": [
                            "Pasta",
                            "Meat"
                          ],
                          "ingredients": [
                            {
                              "measure": "2",
                              "id": "640c2dd963a319ea671e372e"
                            }
                          ]
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "204": {
            "description": "when search has no result"
          }
        }
      }
    },
    "/api/recipes/popular-recipe": {
      "get": {
        "summary": "Get a list of recipes categories",
        "tags": [
          "Receipes"
        ],
        "description": "received an array of strings",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Array of Strings - reccipes",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "favoriteRecipes": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "example": {
                          "_id": "640cd5ac2d9fecf12e889817",
                          "count": 2
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/search": {
      "get": {
        "summary": "Search recipes",
        "tags": [
          "Receipes"
        ],
        "description": "search recipes by key word",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "query",
            "schema": {
              "type": "string",
              "example": "pot"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Array of recipes when search result is no empty",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "searchResult": {
                      "type": "array",
                      "items": {
                        "type": "object"
                      }
                    }
                  }
                }
              }
            }
          },
          "204": {
            "description": "when search has no result"
          }
        }
      }
    },
    "/api/ingredients/": {
      "get": {
        "summary": "Search recipes",
        "tags": [
          "Receipes"
        ],
        "description": "search recipes by key word",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "query",
            "schema": {
              "type": "string",
              "example": "Basil Leaves"
            },
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Array of recipes when search result is no empty",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "searchResult": {
                      "type": "array",
                      "items": {
                        "type": "object"
                      }
                    }
                  }
                }
              }
            }
          },
          "204": {
            "description": "when search has no result"
          }
        }
      }
    },
    "/api/ingredients/list": {
      "get": {
        "summary": "Get a list of ingredients",
        "tags": [
          "Receipes"
        ],
        "description": "received a list of all ingredients",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Array of recipes when search result is no empty",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "searchResult": {
                      "type": "array",
                      "items": {
                        "type": "object"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/ownRecipes": {
      "get": {
        "summary": "Get a list of own recipes",
        "tags": [
          "Own Receipes"
        ],
        "description": "received an array of strings",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "collection of own reccipes",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "status": {
                      "type": "string",
                      "example": "success"
                    },
                    "code": {
                      "type": "number",
                      "example": 200
                    },
                    "data": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "example": {
                          "id": "640cd5ac2d9fecf12e8897fc",
                          "title": "Spaghetti Bolognese",
                          "category": "Beef",
                          "area": "Italian,",
                          "instructions": "Put the onion and oil in a large pan and fry over a fairly high heat for 3-4 mins...",
                          "thumb": "https://www.themealdb.com/images/media/meals/sutysw1468247559.jpg",
                          "preview": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678560401/huqdxgwkvbhsfjqtexsm.jpg",
                          "time": 45,
                          "youtube": "https://www.youtube.com/watch?v=-gF8d-fitkU",
                          "tasgs": [
                            "Pasta",
                            "Meat"
                          ],
                          "ingredients": [
                            {
                              "measure": "2",
                              "id": "640c2dd963a319ea671e372e"
                            }
                          ]
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "when wrong id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "d not found"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/ownRecipes/": {
      "post": {
        "summary": "NOT WORK Get an own recipe by id",
        "tags": [
          "Own Receipes"
        ],
        "description": "received an array of strings",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": {
                "$ref": "#/components/schemas/Recipe"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Own reccipes",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "status": "success",
                    "code": 200,
                    "message": "contact delete",
                    "data": {
                      "result": {
                        "_id": "6440f6d31e3250e37a110af9",
                        "thumb": "https://res.cloudinary.com/djwzlsgzd/image/upload/v1681979091/recipes/ftxurqsca0fajtvbzrjp.jpg",
                        "tags": [],
                        "ingredients": [],
                        "owner": "643ac8bba08cae793c3b2eed",
                        "createdAt": "2023-04-20T08:24:51.731Z",
                        "updatedAt": "2023-04-20T08:24:51.731Z"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/ownRecipes/{id}": {
      "delete": {
        "summary": "Get an own recipe by id",
        "tags": [
          "Own Receipes"
        ],
        "description": "received an array of strings",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "user id",
            "schema": {
              "type": "string",
              "example": "640cd5ac2d9fecf12e8897f0"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Own reccipes",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "example": {
                    "status": "success",
                    "code": 200,
                    "message": "contact delete",
                    "data": {
                      "result": {
                        "_id": "6440f6d31e3250e37a110af9",
                        "thumb": "https://res.cloudinary.com/djwzlsgzd/image/upload/v1681979091/recipes/ftxurqsca0fajtvbzrjp.jpg",
                        "tags": [],
                        "ingredients": [],
                        "owner": "643ac8bba08cae793c3b2eed",
                        "createdAt": "2023-04-20T08:24:51.731Z",
                        "updatedAt": "2023-04-20T08:24:51.731Z"
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "when wrong id",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "d not found"
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/favorite": {
      "get": {
        "summary": "Get a list of favorite recipes",
        "tags": [
          "Favorite"
        ],
        "description": "received list of favorite recipes is an array. With fixed pagination - 4 items per page. If page not setted - return first page. If page in query setted more than a real pages count according to all items - return last awailable page.",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "in": "query",
            "name": "page",
            "schema": {
              "type": "number",
              "example": 2
            },
            "required": false
          }
        ],
        "responses": {
          "200": {
            "description": "Array of recipes when search result is no empty",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "totalFavorites": {
                      "type": "number"
                    },
                    "returnedPage": {
                      "type": "number",
                      "example": 2
                    },
                    "favoriteRecipes": {
                      "type": "array",
                      "items": {
                        "type": "object"
                      }
                    }
                  }
                }
              }
            }
          },
          "204": {
            "description": "when search has no result"
          }
        }
      },
      "post": {
        "summary": "Add recipe to favorites",
        "tags": [
          "Favorite"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "example": {
                "recipeId": "640cd5ac2d9fecf12e8897ef"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Array of recipes when search result is no empty",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "favorites": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      },
                      "example": [
                        "640cd5ag2d9fecf12e8897ef",
                        "640cd5dc2d9fecf12e889817",
                        "640cd5ac2d9fenf12e889823"
                      ]
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/favorite/{id}": {
      "delete": {
        "summary": "Delete recipe from favorites",
        "tags": [
          "Favorite"
        ],
        "description": "received list is an array",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "user id",
            "schema": {
              "type": "string",
              "example": "640cd5ac2d9fecf12e8897ef"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "when search has no result"
          }
        }
      }
    },
    "/api/shopping-list": {
      "get": {
        "summary": "Get a list of ingredients added to shopping list",
        "tags": [
          "Shopping list"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "responses": {
          "200": {
            "description": "Array of ingredients data objects",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "shoppingList": {
                      "type": "array",
                      "items": {
                        "type": "object"
                      }
                    }
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Add an ingredient and its quantity to shpooing list",
        "tags": [
          "Shopping list"
        ],
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/User"
              },
              "example": {
                "id": "005c2dd963a319ea671e368c",
                "iid": "640c2dd963a319ea671e368c",
                "ttl": "Challots",
                "thb": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678564674/ovlvnvcuzttiplnzewm3.png",
                "number": "400 g"
              }
            }
          }
        },
        "responses": {
          "201": {
            "description": "Array of recipes when search result is no empty",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "shoppingList": {
                      "type": "array",
                      "items": {
                        "type": "object",
                        "example": {
                          "id": "005c2dd963a319ea671e368c",
                          "iid": "640c2dd963a319ea671e368c",
                          "ttl": "Challots",
                          "thb": "https://res.cloudinary.com/ddbvbv5sp/image/upload/v1678564674/ovlvnvcuzttiplnzewm3.png",
                          "number": "400 g"
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/shopping-list/{id}": {
      "delete": {
        "summary": "Delete ingredient from shopping list",
        "tags": [
          "Shopping list"
        ],
        "description": "received list is an array",
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "description": "id record to delete",
            "schema": {
              "type": "string",
              "example": "640cd5ac2d9fecf12e8897ef"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "when delete was successful"
          },
          "404": {
            "description": "when search has no result",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "message": {
                      "type": "string",
                      "example": "nothing to delete"
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "User": {
        "type": "object",
        "properties": {
          "id": {
            "type": "string",
            "required": [
              "true",
              "user id is required"
            ]
          },
          "name": {
            "type": "string",
            "required": [
              "true",
              "Set name of user"
            ]
          },
          "email": {
            "type": "string",
            "required": [
              "true",
              "Set email of user"
            ]
          },
          "token": {
            "type": "string"
          }
        }
      },
      "Subscribe": {
        "type": "object",
        "properties": {
          "emailToSubscribe": {
            "type": "string",
            "required": [
              "true"
            ]
          }
        }
      },
      "Recipe": {
        "type": "object",
        "properties": {
          "title": {
            "type": "string",
            "example": "soup"
          },
          "instructios": {
            "type": "string",
            "example": "instr example"
          },
          "category": {
            "type": "string",
            "example": "Beef"
          },
          "description": {
            "type": "string",
            "example": "descr example"
          },
          "thumb": {
            "type": "string",
            "example": "thumb example"
          },
          "time": {
            "type": "string",
            "example": 24
          },
          "ingredients": {
            "type": "array",
            "items": {
              "type": "string"
            },
            "example": [
              "640cd5ac2d9fecf12e889821"
            ]
          },
          "owner": {
            "type": "string",
            "example": "643dab0682ade3006f67ecae"
          },
          "file": {
            "type": "string",
            "format": "binary"
          }
        }
      }
    },
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "description": "JWT Authorization header using the Bearer scheme.",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  }
}